#!/bin/bash
# memory_git_backup.sh - SessionStart hook. Weekly commit + push of memory
# data to a private GitHub repo, for true cross-platform restore.
#
# Reads from ~/.claude/.power-kit-config:
#   POWER_KIT_GIT_BACKUP_REPO=<git remote url>   # set by install.sh
#   POWER_KIT_GIT_BACKUP_ENABLED=true
#
# Throttled: pushes at most once per POWER_KIT_GIT_BACKUP_INTERVAL seconds
# (default 604800 = 7 days). Fires from SessionStart so it never delays
# session shutdown.
#
# Repo layout (committed):
#   claude-mem/         (SQLite DB + chroma)
#   projects/           (per-project memory/*.md, secret-redacted)
#   README.md           (auto-generated, links to power-kit-memory-restore)
#
# Skips silently when: not configured, no network, no git, lock held.

set -u

CONFIG="$HOME/.claude/.power-kit-config"
[ -f "$CONFIG" ] || exit 0
# shellcheck disable=SC1090
. "$CONFIG"
[ "${POWER_KIT_GIT_BACKUP_ENABLED:-false}" = "true" ] || exit 0
[ -n "${POWER_KIT_GIT_BACKUP_REPO:-}" ] || exit 0
command -v git >/dev/null 2>&1 || exit 0
command -v rsync >/dev/null 2>&1 || exit 0

INTERVAL="${POWER_KIT_GIT_BACKUP_INTERVAL:-604800}"
STAMP="$HOME/.claude/.power-kit-last-git-push"
if [ -f "$STAMP" ]; then
    NOW=$(date +%s)
    LAST=$(cat "$STAMP" 2>/dev/null || echo 0)
    if [ "$((NOW - LAST))" -lt "$INTERVAL" ]; then
        exit 0
    fi
fi

# Single-instance lock so two sessions starting close together don't race
LOCK="$HOME/.claude/.power-kit-git-backup.lock"
if ! mkdir "$LOCK" 2>/dev/null; then
    exit 0
fi
trap 'rmdir "$LOCK" 2>/dev/null' EXIT

WORKDIR="$HOME/.claude/.power-kit-git-backup"

# First-run clone, otherwise update existing
if [ ! -d "$WORKDIR/.git" ]; then
    rm -rf "$WORKDIR"
    git clone --quiet --depth 1 "$POWER_KIT_GIT_BACKUP_REPO" "$WORKDIR" 2>/dev/null || {
        # Repo might be empty — init locally and push later
        mkdir -p "$WORKDIR"
        cd "$WORKDIR" || exit 0
        git init --quiet
        git remote add origin "$POWER_KIT_GIT_BACKUP_REPO" 2>/dev/null
    }
fi
cd "$WORKDIR" || exit 0

# Mirror current state into the working tree
mkdir -p "$WORKDIR/claude-mem" "$WORKDIR/projects" 2>/dev/null
if [ -d "$HOME/.claude-mem" ]; then
    rsync -a --delete \
        --exclude='*.db-shm' --exclude='*.db-wal' \
        --exclude='logs/' --exclude='worker.pid' \
        --exclude='.cwd-remap-applied-v1' \
        "$HOME/.claude-mem/" "$WORKDIR/claude-mem/" 2>/dev/null
fi

# shellcheck disable=SC1091
. "$(dirname "$0")/lib/secret_scan.sh" 2>/dev/null || true

if [ -d "$HOME/.claude/projects" ]; then
    find "$HOME/.claude/projects" -type d -name "memory" 2>/dev/null | while read -r src; do
        rel=$(echo "$src" | sed "s|^$HOME/.claude/projects/||")
        out="$WORKDIR/projects/$rel"
        mkdir -p "$out"
        find "$src" -maxdepth 1 -type f 2>/dev/null | while read -r f; do
            base=$(basename "$f")
            case "$base" in
                *.md|*.json|*.jsonl|*.txt)
                    if command -v has_secrets >/dev/null 2>&1 && has_secrets "$f"; then
                        filter_secrets "$f" "$out/$base"
                    else
                        cp "$f" "$out/$base"
                    fi
                    ;;
                *)
                    cp "$f" "$out/$base" 2>/dev/null
                    ;;
            esac
        done
    done
fi

# README so the repo is restorable from a fresh checkout
cat > "$WORKDIR/README.md" <<EOF
# Power-Kit Memory Backup

Auto-generated by claude-power-kit memory_git_backup.sh.

## Layout
- \`claude-mem/\` - claude-mem SQLite DB + Chroma vector store
- \`projects/\` - per-project memory dirs (secret-redacted)

## Restore on a new machine
\`\`\`bash
cd ~/Desktop && git clone <this-repo-url> claude-power-kit
cd claude-power-kit && bash install.sh
power-kit-memory-restore --from-git
\`\`\`

Last push: $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

# Commit + push
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    git add -A 2>/dev/null
    git -c user.email='power-kit@local' -c user.name='power-kit' \
        commit -q -m "memory snapshot $(date -u +%Y-%m-%dT%H:%M:%SZ)" 2>/dev/null
    BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)
    if [ "$BRANCH" = "HEAD" ]; then
        git checkout -q -b main 2>/dev/null
        BRANCH=main
    fi
    git push --quiet origin "$BRANCH" 2>/dev/null || true
fi

date +%s > "$STAMP"
exit 0
